package nz.co.dimu.jspgenerator.dto;

import java.util.Date;

public class DimuBeanDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.id
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.column_id
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private Integer columnId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.title
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.s_title
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String sTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.type
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.tag1
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String tag1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.tag2
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String tag2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.tag3
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String tag3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.tag4
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String tag4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.tag5
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String tag5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.tag6
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String tag6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.tag7
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String tag7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.tag8
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String tag8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.tag9
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String tag9;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.tag10
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String tag10;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.publish_time
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private Date publishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.checker_id
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private Integer checkerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.check_result
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private Integer checkResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.check_date
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private Date checkDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.click_times
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private Integer clickTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.user_id
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.cid
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.score
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private Double score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.cost
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private Double cost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.extern_table
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String externTable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.cdate
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private Date cdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.group_sn
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String groupSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.ext1
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String ext1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.ext3
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String ext3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.ext4
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String ext4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.ext5
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String ext5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.ext6
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String ext6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.ext7
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String ext7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.ext8
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String ext8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.ext9
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String ext9;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.ext10
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String ext10;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.ext11
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String ext11;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.ext12
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String ext12;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.ext13
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String ext13;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.order_pos
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private Integer orderPos;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.order_num
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private Integer orderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.ext17
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String ext17;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.ext18
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String ext18;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.ext19
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String ext19;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.ext20
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String ext20;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.tag11
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String tag11;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.tag12
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String tag12;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.tag13
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String tag13;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.tag14
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String tag14;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.tag15
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String tag15;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.tag16
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String tag16;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.tag17
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String tag17;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.tag18
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String tag18;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.tag19
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String tag19;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.tag20
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String tag20;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.tag21
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String tag21;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.tag22
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String tag22;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.tag23
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String tag23;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.tag24
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String tag24;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.tag25
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String tag25;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.tag26
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String tag26;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.tag27
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String tag27;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.tag28
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String tag28;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.tag29
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String tag29;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.tag30
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String tag30;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.id
     *
     * @return the value of t_news.id
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.id
     *
     * @param id the value for t_news.id
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.column_id
     *
     * @return the value of t_news.column_id
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public Integer getColumnId() {
        return columnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.column_id
     *
     * @param columnId the value for t_news.column_id
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setColumnId(Integer columnId) {
        this.columnId = columnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.title
     *
     * @return the value of t_news.title
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.title
     *
     * @param title the value for t_news.title
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.s_title
     *
     * @return the value of t_news.s_title
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getsTitle() {
        return sTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.s_title
     *
     * @param sTitle the value for t_news.s_title
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setsTitle(String sTitle) {
        this.sTitle = sTitle == null ? null : sTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.type
     *
     * @return the value of t_news.type
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.type
     *
     * @param type the value for t_news.type
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.tag1
     *
     * @return the value of t_news.tag1
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getTag1() {
        return tag1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.tag1
     *
     * @param tag1 the value for t_news.tag1
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setTag1(String tag1) {
        this.tag1 = tag1 == null ? null : tag1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.tag2
     *
     * @return the value of t_news.tag2
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getTag2() {
        return tag2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.tag2
     *
     * @param tag2 the value for t_news.tag2
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setTag2(String tag2) {
        this.tag2 = tag2 == null ? null : tag2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.tag3
     *
     * @return the value of t_news.tag3
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getTag3() {
        return tag3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.tag3
     *
     * @param tag3 the value for t_news.tag3
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setTag3(String tag3) {
        this.tag3 = tag3 == null ? null : tag3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.tag4
     *
     * @return the value of t_news.tag4
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getTag4() {
        return tag4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.tag4
     *
     * @param tag4 the value for t_news.tag4
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setTag4(String tag4) {
        this.tag4 = tag4 == null ? null : tag4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.tag5
     *
     * @return the value of t_news.tag5
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getTag5() {
        return tag5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.tag5
     *
     * @param tag5 the value for t_news.tag5
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setTag5(String tag5) {
        this.tag5 = tag5 == null ? null : tag5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.tag6
     *
     * @return the value of t_news.tag6
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getTag6() {
        return tag6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.tag6
     *
     * @param tag6 the value for t_news.tag6
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setTag6(String tag6) {
        this.tag6 = tag6 == null ? null : tag6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.tag7
     *
     * @return the value of t_news.tag7
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getTag7() {
        return tag7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.tag7
     *
     * @param tag7 the value for t_news.tag7
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setTag7(String tag7) {
        this.tag7 = tag7 == null ? null : tag7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.tag8
     *
     * @return the value of t_news.tag8
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getTag8() {
        return tag8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.tag8
     *
     * @param tag8 the value for t_news.tag8
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setTag8(String tag8) {
        this.tag8 = tag8 == null ? null : tag8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.tag9
     *
     * @return the value of t_news.tag9
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getTag9() {
        return tag9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.tag9
     *
     * @param tag9 the value for t_news.tag9
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setTag9(String tag9) {
        this.tag9 = tag9 == null ? null : tag9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.tag10
     *
     * @return the value of t_news.tag10
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getTag10() {
        return tag10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.tag10
     *
     * @param tag10 the value for t_news.tag10
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setTag10(String tag10) {
        this.tag10 = tag10 == null ? null : tag10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.publish_time
     *
     * @return the value of t_news.publish_time
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.publish_time
     *
     * @param publishTime the value for t_news.publish_time
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.checker_id
     *
     * @return the value of t_news.checker_id
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public Integer getCheckerId() {
        return checkerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.checker_id
     *
     * @param checkerId the value for t_news.checker_id
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setCheckerId(Integer checkerId) {
        this.checkerId = checkerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.check_result
     *
     * @return the value of t_news.check_result
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public Integer getCheckResult() {
        return checkResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.check_result
     *
     * @param checkResult the value for t_news.check_result
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setCheckResult(Integer checkResult) {
        this.checkResult = checkResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.check_date
     *
     * @return the value of t_news.check_date
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public Date getCheckDate() {
        return checkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.check_date
     *
     * @param checkDate the value for t_news.check_date
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setCheckDate(Date checkDate) {
        this.checkDate = checkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.click_times
     *
     * @return the value of t_news.click_times
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public Integer getClickTimes() {
        return clickTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.click_times
     *
     * @param clickTimes the value for t_news.click_times
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setClickTimes(Integer clickTimes) {
        this.clickTimes = clickTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.user_id
     *
     * @return the value of t_news.user_id
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.user_id
     *
     * @param userId the value for t_news.user_id
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.cid
     *
     * @return the value of t_news.cid
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.cid
     *
     * @param cid the value for t_news.cid
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.score
     *
     * @return the value of t_news.score
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.score
     *
     * @param score the value for t_news.score
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setScore(Double score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.cost
     *
     * @return the value of t_news.cost
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public Double getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.cost
     *
     * @param cost the value for t_news.cost
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setCost(Double cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.extern_table
     *
     * @return the value of t_news.extern_table
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getExternTable() {
        return externTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.extern_table
     *
     * @param externTable the value for t_news.extern_table
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setExternTable(String externTable) {
        this.externTable = externTable == null ? null : externTable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.cdate
     *
     * @return the value of t_news.cdate
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public Date getCdate() {
        return cdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.cdate
     *
     * @param cdate the value for t_news.cdate
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setCdate(Date cdate) {
        this.cdate = cdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.group_sn
     *
     * @return the value of t_news.group_sn
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getGroupSn() {
        return groupSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.group_sn
     *
     * @param groupSn the value for t_news.group_sn
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setGroupSn(String groupSn) {
        this.groupSn = groupSn == null ? null : groupSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.ext1
     *
     * @return the value of t_news.ext1
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getExt1() {
        return ext1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.ext1
     *
     * @param ext1 the value for t_news.ext1
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setExt1(String ext1) {
        this.ext1 = ext1 == null ? null : ext1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.ext3
     *
     * @return the value of t_news.ext3
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getExt3() {
        return ext3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.ext3
     *
     * @param ext3 the value for t_news.ext3
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setExt3(String ext3) {
        this.ext3 = ext3 == null ? null : ext3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.ext4
     *
     * @return the value of t_news.ext4
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getExt4() {
        return ext4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.ext4
     *
     * @param ext4 the value for t_news.ext4
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setExt4(String ext4) {
        this.ext4 = ext4 == null ? null : ext4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.ext5
     *
     * @return the value of t_news.ext5
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getExt5() {
        return ext5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.ext5
     *
     * @param ext5 the value for t_news.ext5
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setExt5(String ext5) {
        this.ext5 = ext5 == null ? null : ext5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.ext6
     *
     * @return the value of t_news.ext6
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getExt6() {
        return ext6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.ext6
     *
     * @param ext6 the value for t_news.ext6
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setExt6(String ext6) {
        this.ext6 = ext6 == null ? null : ext6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.ext7
     *
     * @return the value of t_news.ext7
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getExt7() {
        return ext7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.ext7
     *
     * @param ext7 the value for t_news.ext7
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setExt7(String ext7) {
        this.ext7 = ext7 == null ? null : ext7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.ext8
     *
     * @return the value of t_news.ext8
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getExt8() {
        return ext8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.ext8
     *
     * @param ext8 the value for t_news.ext8
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setExt8(String ext8) {
        this.ext8 = ext8 == null ? null : ext8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.ext9
     *
     * @return the value of t_news.ext9
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getExt9() {
        return ext9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.ext9
     *
     * @param ext9 the value for t_news.ext9
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setExt9(String ext9) {
        this.ext9 = ext9 == null ? null : ext9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.ext10
     *
     * @return the value of t_news.ext10
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getExt10() {
        return ext10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.ext10
     *
     * @param ext10 the value for t_news.ext10
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setExt10(String ext10) {
        this.ext10 = ext10 == null ? null : ext10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.ext11
     *
     * @return the value of t_news.ext11
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getExt11() {
        return ext11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.ext11
     *
     * @param ext11 the value for t_news.ext11
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setExt11(String ext11) {
        this.ext11 = ext11 == null ? null : ext11.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.ext12
     *
     * @return the value of t_news.ext12
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getExt12() {
        return ext12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.ext12
     *
     * @param ext12 the value for t_news.ext12
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setExt12(String ext12) {
        this.ext12 = ext12 == null ? null : ext12.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.ext13
     *
     * @return the value of t_news.ext13
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getExt13() {
        return ext13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.ext13
     *
     * @param ext13 the value for t_news.ext13
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setExt13(String ext13) {
        this.ext13 = ext13 == null ? null : ext13.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.order_pos
     *
     * @return the value of t_news.order_pos
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public Integer getOrderPos() {
        return orderPos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.order_pos
     *
     * @param orderPos the value for t_news.order_pos
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setOrderPos(Integer orderPos) {
        this.orderPos = orderPos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.order_num
     *
     * @return the value of t_news.order_num
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.order_num
     *
     * @param orderNum the value for t_news.order_num
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.ext17
     *
     * @return the value of t_news.ext17
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getExt17() {
        return ext17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.ext17
     *
     * @param ext17 the value for t_news.ext17
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setExt17(String ext17) {
        this.ext17 = ext17 == null ? null : ext17.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.ext18
     *
     * @return the value of t_news.ext18
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getExt18() {
        return ext18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.ext18
     *
     * @param ext18 the value for t_news.ext18
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setExt18(String ext18) {
        this.ext18 = ext18 == null ? null : ext18.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.ext19
     *
     * @return the value of t_news.ext19
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getExt19() {
        return ext19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.ext19
     *
     * @param ext19 the value for t_news.ext19
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setExt19(String ext19) {
        this.ext19 = ext19 == null ? null : ext19.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.ext20
     *
     * @return the value of t_news.ext20
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getExt20() {
        return ext20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.ext20
     *
     * @param ext20 the value for t_news.ext20
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setExt20(String ext20) {
        this.ext20 = ext20 == null ? null : ext20.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.tag11
     *
     * @return the value of t_news.tag11
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getTag11() {
        return tag11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.tag11
     *
     * @param tag11 the value for t_news.tag11
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setTag11(String tag11) {
        this.tag11 = tag11 == null ? null : tag11.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.tag12
     *
     * @return the value of t_news.tag12
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getTag12() {
        return tag12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.tag12
     *
     * @param tag12 the value for t_news.tag12
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setTag12(String tag12) {
        this.tag12 = tag12 == null ? null : tag12.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.tag13
     *
     * @return the value of t_news.tag13
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getTag13() {
        return tag13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.tag13
     *
     * @param tag13 the value for t_news.tag13
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setTag13(String tag13) {
        this.tag13 = tag13 == null ? null : tag13.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.tag14
     *
     * @return the value of t_news.tag14
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getTag14() {
        return tag14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.tag14
     *
     * @param tag14 the value for t_news.tag14
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setTag14(String tag14) {
        this.tag14 = tag14 == null ? null : tag14.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.tag15
     *
     * @return the value of t_news.tag15
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getTag15() {
        return tag15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.tag15
     *
     * @param tag15 the value for t_news.tag15
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setTag15(String tag15) {
        this.tag15 = tag15 == null ? null : tag15.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.tag16
     *
     * @return the value of t_news.tag16
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getTag16() {
        return tag16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.tag16
     *
     * @param tag16 the value for t_news.tag16
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setTag16(String tag16) {
        this.tag16 = tag16 == null ? null : tag16.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.tag17
     *
     * @return the value of t_news.tag17
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getTag17() {
        return tag17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.tag17
     *
     * @param tag17 the value for t_news.tag17
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setTag17(String tag17) {
        this.tag17 = tag17 == null ? null : tag17.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.tag18
     *
     * @return the value of t_news.tag18
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getTag18() {
        return tag18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.tag18
     *
     * @param tag18 the value for t_news.tag18
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setTag18(String tag18) {
        this.tag18 = tag18 == null ? null : tag18.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.tag19
     *
     * @return the value of t_news.tag19
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getTag19() {
        return tag19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.tag19
     *
     * @param tag19 the value for t_news.tag19
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setTag19(String tag19) {
        this.tag19 = tag19 == null ? null : tag19.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.tag20
     *
     * @return the value of t_news.tag20
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getTag20() {
        return tag20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.tag20
     *
     * @param tag20 the value for t_news.tag20
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setTag20(String tag20) {
        this.tag20 = tag20 == null ? null : tag20.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.tag21
     *
     * @return the value of t_news.tag21
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getTag21() {
        return tag21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.tag21
     *
     * @param tag21 the value for t_news.tag21
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setTag21(String tag21) {
        this.tag21 = tag21 == null ? null : tag21.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.tag22
     *
     * @return the value of t_news.tag22
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getTag22() {
        return tag22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.tag22
     *
     * @param tag22 the value for t_news.tag22
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setTag22(String tag22) {
        this.tag22 = tag22 == null ? null : tag22.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.tag23
     *
     * @return the value of t_news.tag23
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getTag23() {
        return tag23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.tag23
     *
     * @param tag23 the value for t_news.tag23
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setTag23(String tag23) {
        this.tag23 = tag23 == null ? null : tag23.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.tag24
     *
     * @return the value of t_news.tag24
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getTag24() {
        return tag24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.tag24
     *
     * @param tag24 the value for t_news.tag24
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setTag24(String tag24) {
        this.tag24 = tag24 == null ? null : tag24.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.tag25
     *
     * @return the value of t_news.tag25
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getTag25() {
        return tag25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.tag25
     *
     * @param tag25 the value for t_news.tag25
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setTag25(String tag25) {
        this.tag25 = tag25 == null ? null : tag25.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.tag26
     *
     * @return the value of t_news.tag26
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getTag26() {
        return tag26;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.tag26
     *
     * @param tag26 the value for t_news.tag26
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setTag26(String tag26) {
        this.tag26 = tag26 == null ? null : tag26.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.tag27
     *
     * @return the value of t_news.tag27
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getTag27() {
        return tag27;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.tag27
     *
     * @param tag27 the value for t_news.tag27
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setTag27(String tag27) {
        this.tag27 = tag27 == null ? null : tag27.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.tag28
     *
     * @return the value of t_news.tag28
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getTag28() {
        return tag28;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.tag28
     *
     * @param tag28 the value for t_news.tag28
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setTag28(String tag28) {
        this.tag28 = tag28 == null ? null : tag28.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.tag29
     *
     * @return the value of t_news.tag29
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getTag29() {
        return tag29;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.tag29
     *
     * @param tag29 the value for t_news.tag29
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setTag29(String tag29) {
        this.tag29 = tag29 == null ? null : tag29.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.tag30
     *
     * @return the value of t_news.tag30
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getTag30() {
        return tag30;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.tag30
     *
     * @param tag30 the value for t_news.tag30
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setTag30(String tag30) {
        this.tag30 = tag30 == null ? null : tag30.trim();
    }
}