package nz.co.dimu.jspgenerator.dto;

public class DimuBeanDoWithBLOBs extends DimuBeanDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.ext2
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String ext2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.ext14
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String ext14;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.ext15
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String ext15;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.ext16
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    private String ext16;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.ext2
     *
     * @return the value of t_news.ext2
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getExt2() {
        return ext2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.ext2
     *
     * @param ext2 the value for t_news.ext2
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setExt2(String ext2) {
        this.ext2 = ext2 == null ? null : ext2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.ext14
     *
     * @return the value of t_news.ext14
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getExt14() {
        return ext14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.ext14
     *
     * @param ext14 the value for t_news.ext14
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setExt14(String ext14) {
        this.ext14 = ext14 == null ? null : ext14.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.ext15
     *
     * @return the value of t_news.ext15
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getExt15() {
        return ext15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.ext15
     *
     * @param ext15 the value for t_news.ext15
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setExt15(String ext15) {
        this.ext15 = ext15 == null ? null : ext15.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.ext16
     *
     * @return the value of t_news.ext16
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public String getExt16() {
        return ext16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.ext16
     *
     * @param ext16 the value for t_news.ext16
     *
     * @mbg.generated Fri Feb 01 15:07:01 NZDT 2019
     */
    public void setExt16(String ext16) {
        this.ext16 = ext16 == null ? null : ext16.trim();
    }
}